version: '3.1'
services:
  mysql:
    hostname: mysql
    image: mysql
    container_name: user-sql
    volumes:
      - db-data:/var/lib/user-sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - ms_network


networks:
  ms_network:
volumes:
  db-data: